baseurl:
title: Eshed Schacham
author: Eshed Schacham
email: ashdnazg@gmail.com
description: Ramblings on code and life
name: ashdnazg
minima:
  social_links:
    github: ashdnazg
    linkedin: eshed-shaham
    mastodon:
     - username: ashdnazg
       instance: fosstodon.org

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: minima
permalink: /articles/:short_year/:title
future: true
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: master
