baseurl:
title: Eshed Shaham
author: Eshed Shaham
email: ashdnazg@gmail.com
description: Ramblings on code and life
name: ashdnazg
github_username: ashdnazg
linkedin_username: eshed-shaham
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: minima
permalink: /articles/:short_year/:title
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: master
